engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - src/sulfur/tests/
  - src/sulfur/tests/data/