engines:
  duplication:
    enabled: true
    config:
      languages:
        - python:
            mass_threshold: 50
  fixme:
    enabled: true
  radon:
    enabled: true
    min
ratings:
  paths:
  - "**.py"
exclude_paths:
  - src/sulfur/tests/
  - src/sulfur/tests/data/